import os
import warnings

from flask import Flask, json, jsonify, request, send_from_directory
from flask_cors import CORS, cross_origin

from server.logger import get_logger
from server.datasets import Datasets

# Globals
FOLDER_PATH = os.path.abspath(os.path.dirname(__file__))
STATIC_FOLDER_PATH = os.path.join(FOLDER_PATH, "static")
LOGGER = get_logger(__name__)


# Create a Flask server.
app = Flask(__name__, static_url_path="/static")

# Enable CORS
cors = CORS(app, automatic_options=True)
app.config["CORS_HEADERS"] = "Content-Type"


class HTTPServer:
    """
    HTTP Server Class.
    """

    def __init__(self, args):
        LOGGER.info(f"{type(self).__name__} mode enabled.")
        self.data_dir = os.path.abspath(args.args["data_dir"])

        # Check if the directory exists.
        HTTPServer._check_data_dir_exists(self.data_dir)

        # TODO: (surajk) Make sure there is a check to ensure it is generated by JIT profiler.
        self.experiments = os.listdir(self.data_dir)
        LOGGER.info(f"[REPORT] {len(self.experiments)} JIT profiles will be loaded! ")
        self.handle_routes()

    @staticmethod
    def _check_data_dir_exists(data_dir):
        """
        Internal method to check if the data_dir exists. If not, raise an
        exception and exit the program.
        """
        _is_dir = os.path.exists(data_dir)

        if not _is_dir:
            message = f"It looks like {data_dir} is an invalid directory."
            LOGGER.error(message)
            exit(1)

    def load(self) -> None:
        self.profiles = Datasets(data_dir=self.data_dir)
        self.timeline = None

    def start(self, host: str, port: int) -> None:
        """
        Launch the Flask application.

        :param host: host to run API server
        :param port: port to run API server
        :return: None
        """
        LOGGER.info("Starting the API service")
        app.run(host=host, port=port, threaded=True, debug=True)

    @staticmethod
    def emit_json(endpoint: str, json_data: any) -> str:
        """
        Emit the json data to the endpoint

        :param endpoint: Endpoint to emit information to.
        :param json_data: Data to emit to the endpoint
        :return response: Response packed with data (in JSON format).
        """
        try:
            response = app.response_class(
                response=json.dumps(json_data),
                status=200,
                mimetype="application/json",
            )
            response.headers.add("Access-Control-Allow-Headers", "*")
            response.headers.add("Access-Control-Allow-Methods", "*")
            return response
        except ValueError:
            warnings.warn(f"[API: {endpoint}] emits no data.")
            return jsonify(isError=True, message="Error", statusCode=500)

    def handle_routes(self):
        @app.route("/")
        @cross_origin()
        def index():
            return app.send_static_file("index.html")

        @app.route("/fetch_experiments", methods=["GET"])
        @cross_origin()
        def fetch_experiments():
            sorted_experiments = self.profiles.sort_by_date()
            return jsonify(experiments=sorted_experiments)

        @app.route("/set_experiment", methods=["POST"])
        @cross_origin()
        def set_experiment():
            request_context = request.json
            experiment = request_context["experiment"]
            self.timeline = self.profiles.get_profile(experiment)
            metadata = self.timeline.get_metadata(experiment)
            return jsonify(metadata)

        @app.route("/fetch_timeline", methods=["POST"])
        @cross_origin()
        def fetch_timeline():
            if self.timeline is not None:
                request_context = request.json
                window_start = request_context["window_start"]
                window_end = request_context["window_end"]
                timeline = self.timeline.get_timeline(window_start, window_end)
                return jsonify(timeline)
            else:
                return jsonify({})

        @app.route("/fetch_summary", methods=["POST"])
        @cross_origin()
        def fetch_summary():
            if self.timeline is not None:
                summary = self.timeline.get_summary()
                return jsonify(summary)
            else:
                return jsonify({})

        @app.route("/fetch_event_summary", methods=["GET"])
        @cross_origin()
        def fetch_event_summary():
            if self.timeline is not None:
                event_summary = self.timeline.get_event_summary(["range"])
                return jsonify(event_summary)
            else:
                return jsonify({})

        @app.route("/fetch_background_summary", methods=["GET"])
        @cross_origin()
        def fetch_background_summary():
            if self.timeline is not None:
                bkg_summary = self.timeline.get_event_summary(["background"])
                return jsonify(bkg_summary)
            else:
                return jsonify({})

        @app.route("/static/<filename>", methods=["GET"])
        def get_json(filename):
            return send_from_directory(STATIC_FOLDER_PATH, filename)
