export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const UPDATE_EXPERIMENT = 'UPDATE_EXPERIMENT';
