export const FETCH_BACKGROUND_SUMMARY = 'FETCH_BACKGROUND_SUMMART';
export const FETCH_EVENT_SUMMARY = 'FETCH_EVENT_SUMMARY';
export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
export const FETCH_METADATA = 'FETCH_METADATA';
export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const UPDATE_EVENT_SUMMARY = 'UPDATE_EVENT_SUMMARY';
